-- 037: Exercise metrics — stress index + stimulus-fatigue ratio
-- Adds per-exercise metrics to weight_log for trainer analytics

ALTER TABLE weight_log
  ADD COLUMN IF NOT EXISTS stress_index NUMERIC,
  ADD COLUMN IF NOT EXISTS stimulus_rating SMALLINT CHECK (stimulus_rating BETWEEN 1 AND 5),
  ADD COLUMN IF NOT EXISTS fatigue_rating SMALLINT CHECK (fatigue_rating BETWEEN 1 AND 5);

-- Index for efficient exercise analytics queries (trainer charts)
CREATE INDEX IF NOT EXISTS idx_weight_log_exercise_metrics
  ON weight_log (client_id, exercise_name, session_date DESC)
  WHERE stress_index IS NOT NULL;

COMMENT ON COLUMN weight_log.stress_index IS 'Auto-calculated: sum(weight × reps) × intensity_factor(RIR). Higher = more mechanical stress.';
COMMENT ON COLUMN weight_log.stimulus_rating IS 'Client-rated 1-5: perceived muscle stimulus (pump, mind-muscle connection).';
COMMENT ON COLUMN weight_log.fatigue_rating IS 'Client-rated 1-5: perceived systemic fatigue generated by the exercise.';
